owner: CronoTech
repo: uptime

sites:
  - name: CronoTracker App
    url: https://app.cronotracker.com
    headers:
      X-Upptime-Token: $UPPTIME_TOKEN
  - name: CronoTracker API
    url: https://app.cronotracker.com/api/version
    headers:
      X-Upptime-Token: $UPPTIME_TOKEN
    expectedStatusCodes:
      - 200
      - 401
      - 403
  - name: CronoTech Consulting Home Landing
    url: https://cronotech.org
    headers:
      X-Upptime-Token: $UPPTIME_TOKEN

status-website:
  cname: status.cronotracker.com
  favicon: https://app.cronotracker.com/favicon.ico
  logoUrl: https://app.cronotracker.com/favicon.ico
  name: CronoTracker Status
  introTitle: CronoTracker System Status
  introMessage: Real-time status and incident history for CronoTracker services.
  themeUrl: https://status.cronotracker.com/dark.css
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: CronoTracker App
      href: https://app.cronotracker.com
      
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"

assignees:
  - killer6oose
