owner: cronotech
repo: uptime

sites:
  - name: CronoTracker App
    url: https://app.cronotracker.com
  - name: CronoTracker API
    url: https://app.cronotracker.com/api/version
  - name: CronoTech Consulting Home Landing
    url: https://cronotech.org

status-website:
  cname: status.cronotracker.com
  name: CronoTracker Status
  logoUrl: https://app.cronotracker.com/favicon.ico
  introTitle: CronoTracker System Status
  introMessage: Real-time status and incident history for CronoTracker services
  
  navbar:
    - title: CronoTech Status
      href: /

assignees:
  - killer6oose
